name: Test Workflow
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hub Test Script
        shell: bash
        run: |
          cd ..
          curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
          export PATH="$(pwd)/bin:$PATH"
          echo "github.com:\n- user: JLLeitschuh" > ~/.config/hub
          git config --global hub.protocol https
          git config --global user.email "Jonathan.Leitschuh@gmail.com"
          git config --global user.name "Jonathan Leitschuh"
          hub clone jlleitschuh/bad-pom
          cd bad-pom
          git checkout -b test-fix
          echo "A test update" > TEST.md
          git add .
          git commit -am "A test commit"
          git push origin test-fix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
