name: Test Workflow
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Hub Test Script
        shell: bash
        run: |
          REPO_PATH=$(pwd)
          cd ..
          curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
          export PATH="$(pwd)/bin:$PATH"
          mkdir ~/.config
          cat >>~/.config/hub <<EOF
          github.com:
          - user: $GITHUB_ACTOR
          EOF
          tail ~/.config/hub
          cat >>~/.netrc <<EOF
          machine github.com
            login $GITHUB_ACTOR
            password $GITHUB_TOKEN
          EOF
          git config --global hub.protocol https
          git config --global user.email "Jonathan.Leitschuh@gmail.com"
          git config --global user.name "Jonathan Leitschuh"
          hub clone jlleitschuh/bad-pom
          cd bad-pom
          git checkout -b test-fix
          echo "A test update" > TEST.md
          git add .
          git commit -am "A test commit"
          echo "Attempting Push"
          git push origin test-fix
          hub pull-request --file "$REPO_PATH/PR_MESSAGE.txt"
        env:
          GITHUB_TOKEN: ${{ secrets.ENHANCED_GITHUB_TOKEN }}
