name: Test Workflow
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hub Test Script
        shell: bash
        run: |
          cd ..
          curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
          export PATH="$(pwd)/bin:$PATH"
          hub clone jlleitschuh/bad-pom
          cd bad-pom
          hub pr list  # list pull requests in the current repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
